# .cirrus.yml

tasks:
  -name: install dependencies
  instance:
      image: ubantu:20.04
   script:
     - apt-get update
     - apt-get install -y python3.9
  - name: run script
  script:
    - pip install --upgrade google-api-python-client feedparser
    - python post_rss_feed_to_blogger.py
 # .cirrus.yml

