task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 240m  
  container:
      image: ubuntu:20.04
Script:
- apt-get update
- apt-get install -y python3.9
- pip install --upgrade google-api-python-client feedparser

 script:
 - pip install --upgrade google-api-python-client feedparser
 - python post_rss_feed_to_blogger.py


